/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pgmio */

#ifndef _Included_pgmio
#define _Included_pgmio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pgmio
 * Method:    getPGM
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pgmio_getPGM
  (JNIEnv *, jobject, jstring);

/*
 * Class:     pgmio
 * Method:    savePGM
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pgmio_savePGM
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
